name: Run ThreadSanitizer

on:
  push:

jobs:
  run-tsan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: a47a55bfee0c0bbd5724953d89144f55544f6a52

      - name: Build repository 
        run: | 
          ./fbt
          
      - name: Install ThreadSanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Thread Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
            #!/bin/bash
            set +e

            files=$(find . -type f)
            TIMEOUT_DURATION=10

            for file in $files; do
                if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                    include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                    if ! timeout 60 clang -I "$include_dirs" -fsanitize=thread -fPIE -pie -O2  -g "$file" -o ./compiled.out > /dev/null 2> /tmp/clang_errors.txt; then
                        exit_code=$?
                        if [ $exit_code -eq 1 ]; then
                            continue
                        fi
                        continue 
                    fi

                    timeout $TIMEOUT_DURATION ./compiled.out
                    rm -f ./compiled.out
                fi
            done
